<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>PerformanceMonitor.Tests</AssemblyName>
    <RootNamespace>PerformanceMonitor.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PerformanceMonitor\PerformanceMonitor.csproj" />
  </ItemGroup>
</Project>
